# Generated by Django 3.2.9 on 2021-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('api_url', models.CharField(default=None, max_length=200)),
                ('upc_schema', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
