# Generated by Django 3.2.9 on 2021-11-17 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcs', '0002_rename_upc_schema_merchant_query_fmt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='api_url',
            field=models.CharField(default=None, max_length=200, validators=[django.core.validators.URLValidator(message='Error: Please enter a URL')]),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='query_fmt',
            field=models.CharField(default=None, max_length=50, validators=[django.core.validators.RegexValidator('<upc>', 'Error: Please include <upc> in the query format')]),
        ),
    ]
